### ISSUE TITLE
TODO: 

### ISSUE THREAD

**Issue by Tenclea** [Tenclea/YANG#3]
- [x] Add support for SOCKS proxies
- [x] Auto update / Notification if new update available
- [x] Proxy scrapping during checking (every 15 minutes or so)

Open to suggestions, reply in this commit

**Comment by Yunikee** [comment]
yesss

**Comment by Yunikee** [comment]
Hey, add me on my new discord  Yunike#9902

**Comment by cloudware23** [comment]
Hi... I am not able to run the node app.js- I installed the requirements using npm install... After that i used node app.js command in CMD/admin as u said... it says :- not able to locate module './utils/logger' 
What to do here.. please tell me.

**Comment by Tenclea** [comment]
Hi @cloudware23 ,  
Did you make sure to clone the whole repository ?

**Comment by Tenclea** [comment]
Closing this to move into discusisons
